import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/layout/Header";
import Nav from "@/components/layout/Nav";
import "../css/index.css";

const pretendard = localFont({
  src: "../fonts/pretendard/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body className={`${pretendard.className} bg-color-main antialiased`}>
        <Header />
        <div className="flex flex-col sm:flex-row">
          <Nav />
          <main className="flex flex-1 sm:h-[calc(100vh-var(--header-height))] sm:overflow-y-scroll">{children}</main>
        </div>
      </body>
    </html>
  );
}
