import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/layout/Header";
import Nav from "@/components/layout/Nav";
import "../css/index.css";

const pretendard = localFont({
  src: "../fonts/pretendard/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body className={`${pretendard.className} bg-[#E5E8EB] antialiased`}>
        <div className="bg-bg-main m-auto w-full max-w-full rounded-[30px] lg:max-w-[1440px]">
          <Header />
          <div className="flex h-fit flex-col sm:flex-row">
            <Nav />
            <main className="flex flex-1 rounded-br-[30px] sm:h-[calc(100vh-var(--header-height))] sm:overflow-y-scroll">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
